unorderable types bugfix in path implementation
The `Nodebase.path` implementation had a `list < int` comparison
which is valid under Python 2 but raises the following exception
in Python 3.

    TypeError: unorderable types: int() < list()