python 3 indexing issues with dictionary views
In Python 3 the dictionary methods `items` and `keys` return
views on the dictionary which do not support indexing.

```python
>>> d = {'a': 1, 'b': 2, 'c': 3}
>>> d.keys()
dict_keys(['b', 'c', 'a'])
>>> d.values()
dict_values([2, 3, 1])
>>> d.keys()[1]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'dict_keys' object does not support indexing
>>> d.values()[1]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'dict_values' object does not support indexing
```

This commit changes the test code that uses the dictionary
methods to support py3.